mov: mov.o
	ld -g mov.o -o mov

mov.o: mov.s
	as -g mov.s -o mov.o


newmov: newmov.o
	ld -g newmov.o -o newmov

newmov.o: newmov.s
	as -g newmov.s -o newmov.o


finalmov: finalmov.o
	ld -g finalmov.o -o finalmov

finalmov.o: finalmov.s
	as -g finalmov.s -o finalmov.o
